name: Deploy prefixes to github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: ./.venv
      - name: Install Python dependencies
        run: poetry install
      - name: run script 
        run: |
            source .venv/bin/activate
            cd ./sources/scripts
            python export_prefixes.py
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./sources/scripts/ns 